using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Pdlc.Domain.Entities;
using Pdlc.Domain.Enums;
using Pdlc.Domain.Interfaces;

namespace Pdlc.Application.PrReview;

public interface IPrReviewService
{
    /// <summary>Fetch PR diff, send to Claude, post inline comments back to ADO PR.</summary>
    Task<PrReviewResult> ReviewPullRequestAsync(ReviewPrRequest request, CancellationToken ct = default);
}

public record ReviewPrRequest(
    string AdoProject,
    string Repository,
    int PullRequestId,
    string PromptVersion = "v1",
    bool PostCommentsToAdo = true
);

public sealed class PrReviewService : IPrReviewService
{
    private readonly IClaudeService _claude;
    private readonly IPromptRepository _prompts;
    private readonly IAdoReposService _adoRepos;
    private readonly IPrReviewRepository _repo;
    private readonly ILogger<PrReviewService> _logger;

    public PrReviewService(
        IClaudeService claude,
        IPromptRepository prompts,
        IAdoReposService adoRepos,
        IPrReviewRepository repo,
        ILogger<PrReviewService> logger)
    {
        _claude = claude;
        _prompts = prompts;
        _adoRepos = adoRepos;
        _repo = repo;
        _logger = logger;
    }

    public async Task<PrReviewResult> ReviewPullRequestAsync(
        ReviewPrRequest request, CancellationToken ct = default)
    {
        _logger.LogInformation("[Stage3b] Reviewing PR #{PrId} in {Project}/{Repo}",
            request.PullRequestId, request.AdoProject, request.Repository);

        // 1. Fetch diff from ADO
        var diff = await _adoRepos.GetPullRequestDiffAsync(
            request.AdoProject, request.Repository, request.PullRequestId, ct);

        if (string.IsNullOrWhiteSpace(diff))
        {
            _logger.LogWarning("[Stage3b] Empty diff for PR #{PrId}", request.PullRequestId);
            diff = "[No diff content available]";
        }

        // 2. Call Claude with the PR review prompt
        var systemPrompt = await _prompts.GetPromptAsync(PdlcStage.PrReview, request.PromptVersion, ct);

        var userMessage = $"""
            Review the following pull request diff.
            Return a JSON array of review comments, each with:
            - filePath (string)
            - lineNumber (int or null)
            - severity ("info" | "warning" | "error" | "security")
            - category ("bug" | "style" | "performance" | "security" | "improvement" | "test-coverage")
            - comment (string — the review text, concise and actionable)
            - suggestion (string or null — code suggestion if applicable)

            PR Diff:
            {diff.Truncate(12000)}
            """;

        var response = await _claude.SendAsync(new ClaudeRequest(
            SystemPrompt: systemPrompt,
            UserMessage: userMessage,
            Stage: PdlcStage.PrReview,
            OperationName: "PrReview"), ct);

        var comments = ParseReviewComments(response.Content);
        _logger.LogInformation("[Stage3b] Claude returned {Count} review comments", comments.Count);

        // 3. Post comments back to ADO PR
        var postedCount = 0;
        if (request.PostCommentsToAdo)
        {
            foreach (var comment in comments)
            {
                var severity = comment.Severity.ToUpperInvariant();
                var content = $"""
                    **[AI Review — {severity}]** `{comment.Category}`

                    {comment.Comment}
                    {(comment.Suggestion is not null ? $"\n```\n{comment.Suggestion}\n```" : string.Empty)}

                    *Generated by PDLC AI Code Review — model: {response.Model}*
                    """;

                await _adoRepos.PostPrCommentAsync(
                    request.AdoProject, request.Repository, request.PullRequestId,
                    new PrComment(comment.FilePath, comment.LineNumber, content, "text"), ct);

                postedCount++;
            }
        }

        // 4. Persist result
        var result = await _repo.AddAsync(new PrReviewResult
        {
            AdoProject = request.AdoProject,
            Repository = request.Repository,
            PullRequestId = request.PullRequestId,
            DiffSummary = diff.Truncate(500),
            ReviewJson = JsonSerializer.Serialize(comments),
            CommentsPosted = postedCount,
            TokensUsed = response.InputTokens + response.OutputTokens,
            ModelVersion = response.Model
        }, ct);

        _logger.LogInformation("[Stage3b] Posted {Posted} comments to PR #{PrId}", postedCount, request.PullRequestId);
        return result;
    }

    private static List<ReviewComment> ParseReviewComments(string content)
    {
        try
        {
            var clean = content
                .Replace("```json", string.Empty)
                .Replace("```", string.Empty)
                .Trim();
            return JsonSerializer.Deserialize<List<ReviewComment>>(clean,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                ?? new List<ReviewComment>();
        }
        catch
        {
            // If Claude returns prose instead of JSON, wrap it as a single general comment
            return new List<ReviewComment>
            {
                new() { FilePath = string.Empty, Severity = "info", Category = "general", Comment = content }
            };
        }
    }

    private sealed class ReviewComment
    {
        public string FilePath { get; set; } = string.Empty;
        public int? LineNumber { get; set; }
        public string Severity { get; set; } = "info";
        public string Category { get; set; } = "improvement";
        public string Comment { get; set; } = string.Empty;
        public string? Suggestion { get; set; }
    }
}

internal static class StringExtensions
{
    public static string Truncate(this string s, int max) =>
        s.Length <= max ? s : s[..max] + "… [truncated]";
}
